const swaggerAutogen = require('swagger-autogen')();
const URI = '/clone-tinder-api';

const outputFile = './swagger_output.json';
const endpointsFiles = ['./server.js'];

const doc = {
  info: {
    version: "1.0.0",
    title: "Clone Tinder API",
    description: "Documentation automatically generated by the <b>swagger.autogen</b> module."
  },
  host: 'rstinder.com',
  basePath: URI,
  schemes: ['http', 'https'],
  consumes: ['application/json'],
  produces: ['application/json'],
  tags: [
    {
      "name": "User",
      "description": "Endpoints"
    }
  ],

  definitions: {
  }
};

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
 // require('./index.js')
});